#!/bin/sh
# postinst script for mauna-cursor-themes
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)

    update-alternatives \
        --install /usr/share/icons/default/index.theme x-cursor-theme \
        /usr/share/icons/Bibata-Modern-Classic/cursor.theme 105

    update-alternatives \
        --install /usr/share/icons/default/index.theme x-cursor-theme \
        /usr/share/icons/Bibata-Modern-Ice/cursor.theme 105

    update-alternatives \
        --install /usr/share/icons/default/index.theme x-cursor-theme \
        /usr/share/icons/Qogir/cursor.theme 105

    update-alternatives \
        --install /usr/share/icons/default/index.theme x-cursor-theme \
        /usr/share/icons/Qogir-Dark/cursor.theme 110

    update-alternatives \
        --install /usr/share/icons/default/index.theme x-cursor-theme \
        /usr/share/icons/XCursor-Pro-Dark/cursor.theme 105

    update-alternatives \
        --install /usr/share/icons/default/index.theme x-cursor-theme \
        /usr/share/icons/XCursor-Pro-Light/cursor.theme 105

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    triggered)

    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
